name: Build and Push Multiple Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # - name: Build and push Docker images
    #   run: |
    #     for file in $(find . -name 'Dockerfile.*'); do
    #       image_name=$(echo $file | sed -e 's/\.\/Dockerfile\.//')
    #       docker buildx build --push --tag "${{ secrets.DOCKER_HUB_USERNAME }}/$image_name:latest" -f $file .
    #     done
