name: Build and Push Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get repository info
        uses: gacts/github-slug@v1
        id: slug
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Hadoop version
        id: get_version
        run: echo "version=$(grep 'HADOOP_VERSION=' Dockerfile.datanode | cut -d '=' -f 2)" >> $GITHUB_OUTPUT

      - name: Build and push NameNode
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.namenode
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/namenode:${{ steps.get_version.outputs.version }}

      - name: Build and push DataNode
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.datanode
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datanode:${{ steps.get_version.outputs.version }}

      - name: Build and push Hadoop
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.hadoop
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hadoop:${{ steps.get_version.outputs.version }}

      - name: Build and push JournalNode
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.journalnode
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/journalnode:${{ steps.get_version.outputs.version }}